name: "Build and Deploy to Github Pages"
on:
  push:
    tags:
      - '*'
jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
  build-haddock-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v21
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Build haddock site
        run: |
          nix build .#combined-plutus-haddock
          mkdir dist
          cp -RL ./result/share/doc/* ./dist/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.ref_name }}
